# Generated by Django 4.1.2 on 2024-02-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_room_created_at_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_at_time',
            new_name='created_at',
        ),
    ]
